---
apiVersion: v1
kind: Service
metadata:
   name: go-app-web-service
   labels:
      app: go-web-app
spec:
  selector:
      app: go-web-app
  type: ClusterIP
  ports:
     - port: 80
       targetPort: 8080
       protocol: TCP
   