---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.20'

        - name: Install dependencies
          run: go mod tidy

        - name: Run tests
          run: go test ./...

    code-quality:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.20'

        - name: Install golangci-lint
          run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

        - name: Run golangci-lint
          run: golangci-lint run ./...